import { cn } from '@/lib/utils';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/navbar';
import Providers from '@/components/providers';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'TrivAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <div
            className={cn(inter.className, 'min-h-screen pt-15 antialiased')}
          >
            <header>
              <div className="fixed inset-x-0 top-0 z-[10] h-15 border-b border-zinc-300 bg-white py-2 dark:bg-gray-950">
                <div className="mx-auto h-full max-w-7xl px-8">
                  <Navbar />
                </div>
              </div>
            </header>
            <main>
              <div className="mx-auto max-w-7xl p-8">{children}</div>
            </main>
            <Toaster position="top-center" />
          </div>
        </Providers>
      </body>
    </html>
  );
}
